city_mapping = {'Akron': 0,
 'Albany': 1,
 'Albuquerque': 2,
 'Alexandria': 3,
 'Allen Park': 4,
 'Anaheim': 5,
 'Anchorage': 6,
 'Annandale': 7,
 'Arden-Arcade': 8,
 'Arlington': 9,
 'Arvin': 10,
 'Athens': 11,
 'Atlanta': 12,
 'Austin': 13,
 'Azusa': 14,
 'Bakersfield': 15,
 'Baltimore': 16,
 'Barstow': 17,
 'Baton Rouge': 18,
 'Bayamon': 19,
 'Bellevue': 20,
 'Beltsville': 21,
 'Berkeley': 22,
 'Bethel Island': 23,
 'Billings': 24,
 'Birmingham': 25,
 'Bismarck': 26,
 'Blaine': 27,
 'Boise (corporate name Boise City)': 28,
 'Bondville': 29,
 'Boston': 30,
 'Bridgeport': 31,
 'Bristol': 32,
 'Brownsville': 33,
 'Buckeye': 34,
 'Buffalo': 35,
 'Burbank': 36,
 'Burlington': 37,
 'Caguas': 38,
 'Calexico': 39,
 'Camden': 40,
 'Campo': 41,
 'Canton': 42,
 'Capitan': 43,
 'Cedar Rapids': 44,
 'Chandler': 45,
 'Charleroi': 46,
 'Charleston': 47,
 'Charlotte': 48,
 'Cheektowaga': 49,
 'Cherry Tree': 50,
 'Chicago': 51,
 'Chico': 52,
 'Chicopee': 53,
 'Chula Vista': 54,
 'Cicero': 55,
 'Cincinnati': 56,
 'Ciudad-Juarez': 57,
 'Clearwater': 58,
 'Cleveland': 59,
 'Clovis': 60,
 'Colorado Springs': 61,
 'Columbus': 62,
 'Compton': 63,
 'Concord': 64,
 'Cornwall': 65,
 'Costa Mesa': 66,
 'Cottonwood West': 67,
 'Cupertino': 68,
 'Dallas': 69,
 'Davenport': 70,
 'Davie': 71,
 'Dayton': 72,
 'Deer Park': 73,
 'Delaware City': 74,
 'Dentsville (Dents)': 75,
 'Denver': 76,
 'Des Moines': 77,
 'Detroit': 78,
 'Duluth': 79,
 'Durham': 80,
 'East Chicago': 81,
 'East Hartford': 82,
 'East Highland Park': 83,
 'East Providence': 84,
 'East Saint Louis': 85,
 'El Cajon': 86,
 'El Centro': 87,
 'El Paso': 88,
 'Elizabeth': 89,
 'Erie': 90,
 'Escondido': 91,
 'Essex': 92,
 'Eugene': 93,
 'Eureka': 94,
 'Evansville': 95,
 'Fairbanks': 96,
 'Fairfield': 97,
 'Fontana': 98,
 'Fort Collins': 99,
 'Fort Lauderdale': 100,
 'Fort Lee': 101,
 'Fort Wayne': 102,
 'Fort Worth': 103,
 'Freehold': 104,
 'Freemansburg': 105,
 'Fremont': 106,
 'Fresno': 107,
 'Glendale': 108,
 'Glendora': 109,
 'Goleta': 110,
 'Grand Junction': 111,
 'Grand Rapids': 112,
 'Grantsville': 113,
 'Great Falls': 114,
 'Greeley': 115,
 'Greenville': 116,
 'Groveton': 117,
 'Guaynabo': 118,
 'Hackensack': 119,
 'Hampton': 120,
 'Harrisville': 121,
 'Hartford': 122,
 'Hollywood': 123,
 'Holtsville': 124,
 'Honolulu': 125,
 'Horicon': 126,
 'Houston': 127,
 'Indianapolis': 128,
 'Indianapolis (Remainder)': 129,
 'Inver Grove Heights (RR name Inver Grove)': 130,
 'Jackson': 131,
 'Jacksonville': 132,
 'Jersey City': 133,
 'Johnstown': 134,
 'Kalispell': 135,
 'Kansas City': 136,
 'Keene': 137,
 'Kingsport': 138,
 'La Habra': 139,
 'Lacey': 140,
 'Lake Elsinore': 141,
 'Lakeville': 142,
 'Lancaster': 143,
 'Lansing': 144,
 'Laredo': 145,
 'Las Vegas': 146,
 'Lemmon Valley-Golden Valley': 147,
 'Lincoln': 148,
 'Lindon': 149,
 'Livermore': 150,
 'Livonia': 151,
 'Lompoc': 152,
 'Londonderry': 153,
 'Long Beach': 154,
 'Longmont': 155,
 'Los Angeles': 156,
 'Louisville': 157,
 'Lowell': 158,
 'Lynn': 159,
 'Madera': 160,
 'Manchester': 161,
 'Maywood': 162,
 'McLean': 163,
 'Medford': 164,
 'Memphis': 165,
 'Mentor': 166,
 'Meridian': 167,
 'Mesa': 168,
 'Mexicali': 169,
 'Miami': 170,
 'Midvale': 171,
 'Milwaukee': 172,
 'Minneapolis': 173,
 'Mira Loma': 174,
 'Mission Viejo': 175,
 'Missoula': 176,
 'Modesto': 177,
 'Morristown': 178,
 'Murray': 179,
 'Napa': 180,
 'Nashville': 181,
 'Nashville-Davidson (Remainder)': 182,
 'Nederland': 183,
 'New Castle': 184,
 'New Haven': 185,
 'New Orleans': 186,
 'New Paris': 187,
 'New York': 188,
 'Newark': 189,
 'Newport News': 190,
 'Niagara Falls': 191,
 'Norfolk': 192,
 'North Las Vegas': 193,
 'North Laurel': 194,
 'North Little Rock': 195,
 'North Valley': 196,
 'Northbrook': 197,
 'Oakland': 198,
 'Ogden': 199,
 'Oklahoma City': 200,
 'Omaha': 201,
 'Ontario': 202,
 'Orlando': 203,
 'Palm Springs': 204,
 'Park Hill': 205,
 'Pasadena': 206,
 'Peoria': 207,
 'Perth Amboy': 208,
 'Peterborough (Peterboro)': 209,
 'Philadelphia': 210,
 'Phoenix': 211,
 'Pico Rivera': 212,
 'Pittsboro': 213,
 'Pittsburgh': 214,
 'Pleasanton': 215,
 'Pomona': 216,
 'Pompano Beach': 217,
 'Ponce': 218,
 'Portland': 219,
 'Presque Isle': 220,
 'Providence': 221,
 'Provo': 222,
 'Raleigh': 223,
 'Redwood City': 224,
 'Reno': 225,
 'Reseda': 226,
 'Richmond': 227,
 'Riverside': 228,
 'Riverton': 229,
 'Roanoke': 230,
 'Rochester': 231,
 'Rockford': 232,
 'Rockwell': 233,
 'Roosevelt': 234,
 'Rosarito': 235,
 'Rosemount': 236,
 'Rubidoux': 237,
 'Rutland': 238,
 'Sacramento': 239,
 'Saint Marks': 240,
 'Saint Petersburg': 241,
 'Salinas': 242,
 'Salt Lake City': 243,
 'San Antonio': 244,
 'San Bernardino': 245,
 'San Diego': 246,
 'San Francisco': 247,
 'San Jose': 248,
 'San Juan': 249,
 'San Pablo': 250,
 'San Rafael': 251,
 'Santa Barbara': 252,
 'Santa Clarita': 253,
 'Santa Maria': 254,
 'Santa Rosa': 255,
 'Schenectady': 256,
 'Schiller Park': 257,
 'Scottsdale': 258,
 'Scranton': 259,
 'Seattle': 260,
 'Sebastopol': 261,
 'Shadyside': 262,
 'Sioux Falls': 263,
 'South Valley': 264,
 'Sparks': 265,
 'Spokane': 266,
 'Springfield': 267,
 'St. Cloud': 268,
 'St. Louis': 269,
 'St. Paul': 270,
 'Stateline': 271,
 'Stockton': 272,
 'Sunrise Manor': 273,
 'Sunset Hills': 274,
 'Surprise': 275,
 'Sutter': 276,
 'Syracuse': 277,
 'Tampa': 278,
 'Tempe': 279,
 'Thomaston': 280,
 'Tijuana': 281,
 'Tualatin': 282,
 'Tucson': 283,
 'Tulsa': 284,
 'Turlock': 285,
 'Underhill (Town of)': 286,
 'Upland': 287,
 'Vallejo': 288,
 'Valrico': 289,
 'Vandenberg Air Force Base': 290,
 'Victorville': 291,
 'Vinton': 292,
 'Virginia Beach': 293,
 'Waco': 294,
 'Warrensville Heights': 295,
 'Washington': 296,
 'Weirton': 297,
 'Welby': 298,
 'Wenden': 299,
 'West Los Angeles': 300,
 'West Yellowstone': 301,
 'Westport': 302,
 'Wichita': 303,
 'Wilkinsburg': 304,
 'Wilmington': 305,
 'Winslow (Township of)': 306,
 'Winston-Salem': 307,
 'Winter Park': 308,
 'Worcester': 309,
 'York': 310
 }

state_mapping = {'Alabama': 1,
 'Alaska': 2,
 'Arizona': 4,
 'Arkansas': 5,
 'California': 6,
 'Colorado': 8,
 'Connecticut': 9,
 'Country Of Mexico': 80,
 'Delaware': 10,
 'District Of Columbia': 11,
 'Florida': 12,
 'Georgia': 13,
 'Hawaii': 15,
 'Idaho': 16,
 'Illinois': 17,
 'Indiana': 18,
 'Iowa': 19,
 'Kansas': 20,
 'Kentucky': 21,
 'Louisiana': 22,
 'Maine': 23,
 'Maryland': 24,
 'Massachusetts': 25,
 'Michigan': 26,
 'Minnesota': 27,
 'Mississippi': 28,
 'Missouri': 29,
 'Montana': 30,
 'Nebraska': 31,
 'Nevada': 32,
 'New Hampshire': 33,
 'New Jersey': 34,
 'New Mexico': 35,
 'New York': 36,
 'North Carolina': 37,
 'North Dakota': 38,
 'Ohio': 39,
 'Oklahoma': 40,
 'Oregon': 41,
 'Pennsylvania': 42,
 'Puerto Rico': 72,
 'Rhode Island': 44,
 'South Carolina': 45,
 'South Dakota': 46,
 'Tennessee': 47,
 'Texas': 48,
 'Utah': 49,
 'Vermont': 50,
 'Virginia': 51,
 'Washington': 53,
 'West Virginia': 54,
 'Wisconsin': 55,
 'Wyoming': 56}

county_mapping = {'Ada': 1,
 'Adair': 1,
 'Adams': 1,
 'Alameda': 1,
 'Albany': 1,
 'Alexandria City': 510,
 'Allegheny': 3,
 'Allen': 3,
 'Anchorage ': 20,
 'Anoka': 3,
 'Arlington': 13,
 'Aroostook': 3,
 'Athens': 9,
 'BAJA CALIFORNIA NORTE': 2,
 'Baltimore': 5,
 'Baltimore (City)': 510,
 'Bayamon': 21,
 'Belmont': 13,
 'Bergen': 3,
 'Berks': 11,
 'Bernalillo': 1,
 'Bexar': 29,
 'Blount': 9,
 'Boulder': 13,
 'Bronx': 5,
 'Brooke': 9,
 'Broward': 11,
 'Bucks': 17,
 'Burleigh': 15,
 'Burlington': 5,
 'Butte': 7,
 'CHIHUAHUA STATE': 6,
 'Caguas': 25,
 'Cambria': 21,
 'Camden': 7,
 'Cameron': 61,
 'Cascade': 13,
 'Cass': 17,
 'Champaign': 19,
 'Charleston': 19,
 'Cherokee': 21,
 'Cheshire': 5,
 'Chittenden': 7,
 'Clallam': 9,
 'Clark': 3,
 'Contra Costa': 13,
 'Converse': 9,
 'Cook': 31,
 'Cumberland': 5,
 'Cuyahoga': 35,
 'Dakota': 37,
 'Dallas': 113,
 'Dauphin': 43,
 'Davidson': 37,
 'DeKalb': 89,
 'Denver': 31,
 'District of Columbia': 1,
 'Dodge': 27,
 'Dorchester': 19,
 'Douglas': 5,
 'Duchesne': 13,
 'Durham': 63,
 'Duval': 31,
 'East Baton Rouge': 33,
 'Edmonson': 61,
 'El Paso': 41,
 'Erie': 29,
 'Essex': 9,
 'Fairbanks North Star ': 90,
 'Fairfax': 59,
 'Fairfield': 1,
 'Flathead': 29,
 'Forsyth': 67,
 'Franklin': 49,
 'Fremont': 13,
 'Fresno': 19,
 'Fulton': 121,
 'Gallatin': 31,
 'Garrett': 23,
 'Greene': 77,
 'Greenville': 45,
 'Guaynabo': 61,
 'Hamilton': 61,
 'Hampden': 13,
 'Hampton City': 650,
 'Hancock': 29,
 'Harris': 201,
 'Harrison': 67,
 'Hartford': 3,
 'Hendricks': 63,
 'Hennepin': 53,
 'Henrico': 87,
 'Hillsborough': 11,
 'Hinds': 49,
 'Honolulu': 3,
 'Howard': 27,
 'Hudson': 17,
 'Humboldt': 23,
 'Imperial': 25,
 'Inyo': 27,
 'Jackson': 29,
 'Jefferson': 111,
 'Kanawha': 39,
 'Kauai': 7,
 'Kay': 71,
 'Kent': 81,
 'Kern': 29,
 'King': 33,
 'La Paz': 12,
 'La Plata': 67,
 'Lackawanna': 69,
 'Lake': 89,
 'Lancaster': 109,
 'Lane': 39,
 'Laramie': 21,
 'Larimer': 69,
 'Lawrence': 73,
 'Lewis and Clark': 49,
 'Linn': 113,
 'Litchfield': 5,
 'Los Angeles': 37,
 'Madera': 39,
 'Maricopa': 13,
 'Marin': 41,
 'Marion': 97,
 'McLennan': 309,
 'Mecklenburg': 119,
 'Medina': 103,
 'Mesa': 77,
 'Miami-Dade': 86,
 'Middlesex': 17,
 'Milwaukee': 79,
 'Minnehaha': 99,
 'Missoula': 63,
 'Monmouth': 25,
 'Monroe': 55,
 'Monterey': 53,
 'Montgomery': 113,
 'Morris': 27,
 'Multnomah': 51,
 'Napa': 55,
 'New Castle': 3,
 'New Haven': 9,
 'New York': 61,
 'Newport News City': 700,
 'Niagara': 63,
 'Norfolk City': 710,
 'Northampton': 95,
 'Oklahoma': 109,
 'Onondaga': 67,
 'Orange': 95,
 'Orleans': 71,
 'Paulding': 223,
 'Peoria': 143,
 'Philadelphia': 101,
 'Pima': 19,
 'Pinellas': 103,
 'Polk': 153,
 'Ponce': 113,
 'Preble': 135,
 "Prince George's": 33,
 'Providence': 7,
 'Pulaski': 119,
 'Queens': 81,
 'Ramsey': 123,
 'Richland': 79,
 'Richmond City': 760,
 'Riverside': 65,
 'Roanoke': 161,
 'Roanoke City': 770,
 'Rockingham': 15,
 'Rowan': 159,
 'Rutland': 21,
 'Sacramento': 67,
 'Saint Clair': 163,
 'Saint Louis': 137,
 'Salt Lake': 35,
 'San Bernardino': 71,
 'San Diego': 73,
 'San Francisco': 75,
 'San Joaquin': 77,
 'San Juan': 127,
 'San Mateo': 81,
 'Sangamon': 167,
 'Santa Barbara': 83,
 'Santa Clara': 85,
 'Santa Cruz': 87,
 'Schenectady': 93,
 'Scott': 163,
 'Sedgwick': 173,
 'Shelby': 157,
 'Solano': 95,
 'Sonoma': 97,
 'Spokane': 63,
 'St. Louis City': 510,
 'Stanislaus': 99,
 'Stark': 151,
 'Stearns': 145,
 'Steuben': 101,
 'Suffolk': 103,
 'Sullivan': 163,
 'Summit': 153,
 'Sutter': 101,
 'Sweetwater': 37,
 'Tarrant': 439,
 'Teton': 39,
 'Thurston': 67,
 'Travis': 453,
 'Tulsa': 143,
 'Uintah': 47,
 'Union': 39,
 'Utah': 49,
 'Vanderburgh': 163,
 'Virginia Beach City': 810,
 'Wake': 183,
 'Wakulla': 129,
 'Washington': 67,
 'Washoe': 31,
 'Wayne': 163,
 'Webb': 479,
 'Weber': 57,
 'Weld': 123,
 'Winnebago': 201,
 'Worcester': 27,
 'Wyandotte': 209,
 'Yellowstone': 111,
 'York': 133}

county_names_dict = {' North Dakota': [],
 'Alabama': ['Jefferson'],
 'Alaska': ['Anchorage ', 'Fairbanks North Star '],
 'American Samoa': [],
 'Arizona': ['La Paz', 'Pima', 'Maricopa'],
 'Arkansas': ['Pulaski'],
 'California': ['Kern',
  'Fresno',
  'San Diego',
  'Santa Barbara',
  'Los Angeles',
  'Orange',
  'Santa Clara',
  'Riverside',
  'San Bernardino',
  'Marin',
  'Butte',
  'Inyo',
  'Contra Costa',
  'Sacramento',
  'Napa',
  'Santa Cruz',
  'Sonoma',
  'Madera',
  'Solano',
  'Sutter',
  'Imperial',
  'Stanislaus',
  'San Francisco',
  'Humboldt',
  'Monterey',
  'San Joaquin',
  'San Mateo',
  'Alameda'],
 'Colorado': ['La Plata',
  'Denver',
  'Jackson',
  'Adams',
  'Larimer',
  'Weld',
  'Boulder',
  'Mesa',
  'El Paso'],
 'Connecticut': ['New Haven', 'Fairfield', 'Litchfield', 'Hartford'],
 'Delaware': ['New Castle'],
 'District of Columbia': [],
 'Florida': ['Duval',
  'Hillsborough',
  'Pinellas',
  'Broward',
  'Miami-Dade',
  'Wakulla',
  'Orange'],
 'Georgia': ['Fulton', 'DeKalb', 'Paulding'],
 'Guam': [],
 'Hawaii': ['Kauai', 'Honolulu'],
 'Idaho': ['Ada'],
 'Illinois': ['Peoria',
  'Cook',
  'Saint Clair',
  'Winnebago',
  'Champaign',
  'Sangamon'],
 'Indiana': ['Marion', 'Hendricks', 'Vanderburgh', 'Allen', 'Lake'],
 'Iowa': ['Linn', 'Scott', 'Polk'],
 'Kansas': ['Wyandotte', 'Sedgwick'],
 'Kentucky': ['Edmonson', 'Jefferson'],
 'Louisiana': ['East Baton Rouge', 'Orleans'],
 'Maine': ['Aroostook', 'Hancock', 'Cumberland'],
 'Maryland': ['Garrett',
  'Dorchester',
  'Baltimore',
  'Howard',
  "Prince George's",
  'Baltimore (City)'],
 'Massachusetts': ['Suffolk', 'Hampden', 'Essex', 'Middlesex', 'Worcester'],
 'Michigan': ['Wayne', 'Kent'],
 'Minnesota': ['Stearns',
  'Dakota',
  'Hennepin',
  'Ramsey',
  'Anoka',
  'Saint Louis'],
 'Mississippi': ['Hinds'],
 'Missouri': ['St. Louis City', 'Jackson', 'Saint Louis', 'Greene'],
 'Montana': ['Yellowstone',
  'Cascade',
  'Lewis and Clark',
  'Missoula',
  'Gallatin',
  'Flathead'],
 'Nebraska': ['Douglas', 'Lancaster'],
 'Nevada': ['Washoe', 'Clark', 'Douglas'],
 'New Hampshire': ['Rockingham', 'Cheshire', 'Hillsborough'],
 'New Jersey': ['Middlesex',
  'Camden',
  'Essex',
  'Union',
  'Morris',
  'Bergen',
  'Hudson',
  'Monmouth',
  'Burlington'],
 'New Mexico': ['Bernalillo'],
 'New York': ['Monroe',
  'Niagara',
  'Bronx',
  'New York',
  'Queens',
  'Steuben',
  'Schenectady',
  'Erie',
  'Albany',
  'Onondaga',
  'Suffolk'],
 'North Carolina': ['Mecklenburg', 'Wake', 'Forsyth', 'Rowan', 'Durham'],
 'Ohio': ['Franklin',
  'Hamilton',
  'Cuyahoga',
  'Athens',
  'Medina',
  'Harrison',
  'Belmont',
  'Lake',
  'Summit',
  'Preble',
  'Stark',
  'Montgomery'],
 'Oklahoma': ['Oklahoma', 'Tulsa', 'Kay', 'Cherokee', 'Adair'],
 'Oregon': ['Multnomah', 'Washington', 'Lane', 'Jackson'],
 'Pennsylvania': ['Dauphin',
  'Allegheny',
  'Washington',
  'Philadelphia',
  'Adams',
  'Erie',
  'Cambria',
  'York',
  'Bucks',
  'Northampton',
  'Lackawanna',
  'Berks',
  'Lawrence'],
 'Puerto Rico': ['San Juan', 'Ponce', 'Bayamon', 'Caguas', 'Guaynabo'],
 'Rhode Island': ['Providence'],
 'South Carolina': ['Charleston', 'Greenville', 'Richland'],
 'South Dakota': ['Union', 'Minnehaha'],
 'Tennessee': ['Blount', 'Shelby', 'Sullivan', 'Davidson'],
 'Texas': ['Jefferson',
  'Bexar',
  'McLennan',
  'Travis',
  'El Paso',
  'Dallas',
  'Tarrant',
  'Harris',
  'Cameron',
  'Webb'],
 'Utah': ['Uintah', 'Utah', 'Salt Lake', 'Weber', 'Duchesne'],
 'Vermont': ['Rutland', 'Chittenden'],
 'Virgin Islands': [],
 'Virginia': ['Hampton City',
  'Fairfax',
  'Henrico',
  'Roanoke',
  'Alexandria City',
  'Norfolk City',
  'Richmond City',
  'Arlington',
  'Newport News City',
  'Roanoke City',
  'Virginia Beach City'],
 'Washington': ['Spokane', 'Clallam', 'Thurston', 'King'],
 'West Virginia': ['Brooke', 'Kanawha', 'Hancock'],
 'Wisconsin': ['Milwaukee', 'Dodge'],
 'Wyoming': ['Fremont', 'Laramie', 'Teton', 'Sweetwater', 'Converse']}



city_detail = {'Ada': ['Boise (corporate name Boise City)', 'Meridian'],
 'Adair': ['Cherry Tree'],
 'Adams': ['Welby'],
 'Alameda': ['Livermore', 'Oakland', 'Pleasanton', 'Fremont', 'Berkeley'],
 'Albany': ['Albany'],
 'Alexandria City': ['Alexandria'],
 'Allegheny': ['Wilkinsburg', 'Pittsburgh'],
 'Allen': ['Fort Wayne'],
 'Anchorage ': ['Anchorage'],
 'Anoka': ['Blaine'],
 'Arlington': ['Arlington'],
 'Aroostook': ['Presque Isle'],
 'Athens': ['Athens'],
 'Baltimore': ['Essex'],
 'Baltimore (City)': ['Baltimore'],
 'Bayamon': ['Bayamon'],
 'Belmont': ['Shadyside'],
 'Bergen': ['Fort Lee', 'Hackensack'],
 'Bernalillo': ['North Valley', 'Albuquerque', 'South Valley'],
 'Bexar': ['San Antonio'],
 'Boulder': ['Longmont'],
 'Bronx': ['New York'],
 'Brooke': ['Weirton'],
 'Broward': ['Fort Lauderdale', 'Davie', 'Pompano Beach', 'Hollywood'],
 'Bucks': ['Bristol'],
 'Burlington': ['Burlington'],
 'Butte': ['Chico'],
 'Caguas': ['Caguas'],
 'Cambria': ['Johnstown'],
 'Camden': ['Camden', 'Winslow (Township of)'],
 'Cameron': ['Brownsville'],
 'Cascade': ['Great Falls'],
 'Champaign': ['Bondville'],
 'Cherokee': ['Park Hill'],
 'Cheshire': ['Keene'],
 'Chittenden': ['Underhill (Town of)', 'Burlington'],
 'Clark': ['Sunrise Manor', 'Las Vegas', 'North Las Vegas'],
 'Contra Costa': ['Concord', 'Bethel Island', 'San Pablo'],
 'Cook': ['Northbrook',
  'Chicago',
  'Schiller Park',
  'Maywood',
  'Lansing',
  'Cicero'],
 'Cumberland': ['Portland'],
 'Cuyahoga': ['Cleveland', 'Warrensville Heights'],
 'Dakota': ['Inver Grove Heights (RR name Inver Grove)',
  'Lakeville',
  'Rosemount'],
 'Dallas': ['Dallas'],
 'Davidson': ['Nashville', 'Nashville-Davidson (Remainder)'],
 'Denver': ['Denver'],
 'Dodge': ['Horicon'],
 'Douglas': ['Omaha', 'Stateline'],
 'Duchesne': ['Roosevelt'],
 'Durham': ['Durham'],
 'Duval': ['Jacksonville'],
 'East Baton Rouge': ['Baton Rouge'],
 'El Paso': ['El Paso', 'Colorado Springs'],
 'Erie': ['Erie', 'Buffalo', 'Cheektowaga'],
 'Essex': ['Newark', 'Lynn'],
 'Fairbanks North Star ': ['Fairbanks'],
 'Fairfax': ['Groveton', 'Springfield', 'Annandale', 'McLean'],
 'Fairfield': ['Westport', 'Bridgeport'],
 'Flathead': ['Kalispell'],
 'Forsyth': ['Winston-Salem'],
 'Franklin': ['Columbus'],
 'Fremont': ['Riverton'],
 'Fresno': ['Fresno', 'Clovis'],
 'Fulton': ['Atlanta'],
 'Gallatin': ['West Yellowstone'],
 'Garrett': ['Grantsville'],
 'Greene': ['Springfield'],
 'Greenville': ['Greenville'],
 'Guaynabo': ['Guaynabo'],
 'Hamilton': ['Cincinnati'],
 'Hampden': ['Springfield', 'Chicopee'],
 'Hampton City': ['Hampton'],
 'Hancock': ['Weirton'],
 'Harris': ['Houston', 'Deer Park'],
 'Hartford': ['Hartford', 'East Hartford'],
 'Hendricks': ['Pittsboro'],
 'Hennepin': ['Minneapolis'],
 'Henrico': ['East Highland Park'],
 'Hillsborough': ['Tampa',
  'Manchester',
  'Valrico',
  'Peterborough (Peterboro)'],
 'Hinds': ['Jackson'],
 'Honolulu': ['Honolulu'],
 'Howard': ['North Laurel'],
 'Hudson': ['Jersey City'],
 'Humboldt': ['Eureka'],
 'Imperial': ['Calexico', 'El Centro'],
 'Jackson': ['Kansas City', 'Medford'],
 'Jefferson': ['Nederland', 'Birmingham', 'Louisville', 'Fairfield'],
 'Kanawha': ['Charleston'],
 'Kent': ['Grand Rapids'],
 'Kern': ['Bakersfield', 'Arvin'],
 'King': ['Seattle', 'Bellevue'],
 'La Paz': ['Wenden'],
 'Lackawanna': ['Scranton'],
 'Lake': ['Mentor', 'East Chicago'],
 'Lancaster': ['Lincoln'],
 'Lane': ['Eugene'],
 'Larimer': ['Fort Collins'],
 'Lawrence': ['New Castle'],
 'Linn': ['Cedar Rapids'],
 'Litchfield': ['Thomaston', 'Cornwall'],
 'Los Angeles': ['West Los Angeles',
  'Los Angeles',
  'Reseda',
  'Compton',
  'Pico Rivera',
  'Pomona',
  'Pasadena',
  'Santa Clarita',
  'Lancaster',
  'Long Beach',
  'Azusa',
  'Glendora',
  'Burbank'],
 'Madera': ['Madera'],
 'Maricopa': ['Scottsdale',
  'Phoenix',
  'Chandler',
  'Buckeye',
  'Tempe',
  'Surprise',
  'Mesa',
  'Glendale'],
 'Marin': ['San Rafael'],
 'Marion': ['Indianapolis', 'Indianapolis (Remainder)'],
 'McLennan': ['Waco'],
 'Mecklenburg': ['Charlotte'],
 'Mesa': ['Grand Junction'],
 'Miami-Dade': ['Miami'],
 'Middlesex': ['Perth Amboy', 'Lowell'],
 'Milwaukee': ['Milwaukee'],
 'Minnehaha': ['Sioux Falls'],
 'Missoula': ['Missoula'],
 'Monmouth': ['Freehold'],
 'Monroe': ['Rochester'],
 'Monterey': ['Salinas'],
 'Montgomery': ['Dayton'],
 'Morris': ['Morristown'],
 'Multnomah': ['Portland'],
 'Napa': ['Napa'],
 'New Castle': ['Delaware City', 'Wilmington'],
 'New Haven': ['New Haven'],
 'New York': ['New York'],
 'Newport News City': ['Newport News'],
 'Niagara': ['Niagara Falls'],
 'Norfolk City': ['Norfolk'],
 'Northampton': ['Freemansburg'],
 'Oklahoma': ['Oklahoma City'],
 'Onondaga': ['Syracuse'],
 'Orange': ['Mission Viejo',
  'Anaheim',
  'Orlando',
  'Costa Mesa',
  'Winter Park',
  'La Habra'],
 'Orleans': ['New Orleans'],
 'Peoria': ['Peoria'],
 'Philadelphia': ['Philadelphia'],
 'Pima': ['Tucson'],
 'Pinellas': ['Clearwater', 'Saint Petersburg'],
 'Polk': ['Des Moines'],
 'Ponce': ['Ponce'],
 'Preble': ['New Paris'],
 "Prince George's": ['Beltsville'],
 'Providence': ['East Providence', 'Providence'],
 'Pulaski': ['North Little Rock'],
 'Queens': ['New York'],
 'Ramsey': ['St. Paul'],
 'Richland': ['Dentsville (Dents)'],
 'Richmond City': ['Richmond'],
 'Riverside': ['Rubidoux',
  'Mira Loma',
  'Lake Elsinore',
  'Riverside',
  'Palm Springs'],
 'Roanoke': ['Vinton'],
 'Roanoke City': ['Roanoke'],
 'Rockingham': ['Londonderry'],
 'Rowan': ['Rockwell'],
 'Rutland': ['Rutland'],
 'Sacramento': ['Arden-Arcade', 'Sacramento'],
 'Saint Clair': ['East Saint Louis'],
 'Saint Louis': ['Sunset Hills', 'Duluth'],
 'Salt Lake': ['Salt Lake City', 'Midvale', 'Cottonwood West', 'Murray'],
 'San Bernardino': ['Ontario',
  'Victorville',
  'San Bernardino',
  'Barstow',
  'Upland',
  'Fontana'],
 'San Diego': ['San Diego', 'El Cajon', 'Campo', 'Chula Vista', 'Escondido'],
 'San Francisco': ['San Francisco'],
 'San Joaquin': ['Stockton'],
 'San Juan': ['San Juan'],
 'San Mateo': ['Redwood City'],
 'Sangamon': ['Springfield'],
 'Santa Barbara': ['Capitan',
  'Goleta',
  'Vandenberg Air Force Base',
  'Santa Maria',
  'Santa Barbara',
  'Lompoc'],
 'Santa Clara': ['Cupertino', 'San Jose'],
 'Santa Cruz': ['Davenport'],
 'Schenectady': ['Schenectady'],
 'Scott': ['Davenport'],
 'Sedgwick': ['Wichita'],
 'Shelby': ['Memphis'],
 'Solano': ['Vallejo'],
 'Sonoma': ['Santa Rosa', 'Sebastopol'],
 'Spokane': ['Spokane'],
 'St. Louis City': ['St. Louis'],
 'Stanislaus': ['Modesto', 'Turlock'],
 'Stark': ['Canton'],
 'Stearns': ['St. Cloud'],
 'Suffolk': ['Boston', 'Holtsville'],
 'Sullivan': ['Kingsport'],
 'Summit': ['Akron'],
 'Sutter': ['Sutter'],
 'Tarrant': ['Fort Worth', 'Arlington'],
 'Thurston': ['Lacey'],
 'Travis': ['Austin'],
 'Tulsa': ['Tulsa'],
 'Union': ['Elizabeth'],
 'Utah': ['Lindon', 'Provo'],
 'Vanderburgh': ['Evansville'],
 'Virginia Beach City': ['Virginia Beach'],
 'Wake': ['Raleigh'],
 'Wakulla': ['Saint Marks'],
 'Washington': ['Charleroi', 'Tualatin'],
 'Washoe': ['Lemmon Valley-Golden Valley', 'Reno', 'Sparks'],
 'Wayne': ['Detroit', 'Livonia', 'Allen Park'],
 'Webb': ['Laredo'],
 'Weber': ['Ogden', 'Harrisville'],
 'Weld': ['Greeley'],
 'Winnebago': ['Rockford'],
 'Worcester': ['Worcester'],
 'Wyandotte': ['Kansas City'],
 'Yellowstone': ['Billings'],
 'York': ['York']}

chart_res = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

state_abb = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "U.S. Virgin Islands": "VI",
}